<?php

namespace AppBundle\Repository;

/**
 * DocPatientRelationshipsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocPatientRelationshipsRepository extends \Doctrine\ORM\EntityRepository
{
}
