<?php

namespace AppBundle\Repository;

/**
 * InvestigationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvestigationRepository extends \Doctrine\ORM\EntityRepository
{
}
