app:
    resource: '@AppBundle/Controller/'
    type: annotation

easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/AdminController.php'
    prefix: /admin
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"